name: Upload to PyPi

on:
  release:
    types:
      - published

jobs:

  upload-to-pypi:
    name: Upload to Pypi
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          architecture: x64

      - name: install dependencies
        run: |
          python --version
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install .[pypi]

      - name: build release binaries
        run: |
          python3 -m build

      - name: publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
